#!/usr/bin/env python3
"""
sync_availability.py

Pulls the Airbnb and Booking.com calendar export (iCal) feeds, merges every
booked date range from both, and writes assets/availability.json in the
exact format booking.html already reads.

This is the piece that needs to run on a schedule once hosting is chosen
(e.g. a GitHub Action on a cron, a Cloudflare Worker cron trigger, a Netlify
scheduled function). It has no dependency on which host you pick — it's a
plain script that reads two URLs and writes one JSON file.

Usage:
    python3 sync_availability.py

Configure the two feed URLs below, or pass them as environment variables
AIRBNB_ICAL_URL / BOOKING_ICAL_URL so the real URLs never have to be
committed to the site's source code.
"""

import json
import os
import re
import sys
import urllib.request
from datetime import date, datetime, timedelta, timezone

AIRBNB_ICAL_URL = os.environ.get("AIRBNB_ICAL_URL", "")
BOOKING_ICAL_URL = os.environ.get("BOOKING_ICAL_URL", "")

OUTPUT_PATH = os.environ.get("AVAILABILITY_JSON_PATH", "assets/availability.json")


def fetch(url_or_path):
    """Fetch ICS text from a URL, or read it from a local file (for testing)."""
    if url_or_path.startswith("http://") or url_or_path.startswith("https://"):
        with urllib.request.urlopen(url_or_path, timeout=20) as resp:
            return resp.read().decode("utf-8", errors="replace")
    with open(url_or_path, encoding="utf-8") as f:
        return f.read()


def parse_ics_date(value):
    """Parse a DTSTART/DTEND value into a date object.
    Handles both VALUE=DATE (YYYYMMDD) and full DATETIME (YYYYMMDDTHHMMSSZ)."""
    value = value.strip()
    if "T" in value:
        value = value.split("T")[0]
    return datetime.strptime(value, "%Y%m%d").date()


def extract_busy_ranges(ics_text):
    """Return a list of (start_date, end_date) tuples from an ICS feed.
    end_date follows the iCal convention: it's the checkout day, i.e.
    NOT itself occupied — the range is [start, end)."""
    ranges = []
    events = ics_text.split("BEGIN:VEVENT")[1:]
    for block in events:
        block = block.split("END:VEVENT")[0]
        start_match = re.search(r"DTSTART[^:]*:(\S+)", block)
        end_match = re.search(r"DTEND[^:]*:(\S+)", block)
        if not start_match or not end_match:
            continue
        try:
            start = parse_ics_date(start_match.group(1))
            end = parse_ics_date(end_match.group(1))
        except ValueError:
            continue
        if end > start:
            ranges.append((start, end))
    return ranges


def expand_to_dates(ranges):
    """Turn (start, end) ranges into a sorted, deduplicated list of
    individual YYYY-MM-DD strings, excluding the checkout day itself."""
    days = set()
    for start, end in ranges:
        d = start
        while d < end:
            days.add(d.isoformat())
            d += timedelta(days=1)
    return sorted(days)


def main():
    if not AIRBNB_ICAL_URL and not BOOKING_ICAL_URL:
        print("No feed URLs configured. Set AIRBNB_ICAL_URL / BOOKING_ICAL_URL.", file=sys.stderr)
        sys.exit(1)

    all_ranges = []
    for name, url in [("Airbnb", AIRBNB_ICAL_URL), ("Booking.com", BOOKING_ICAL_URL)]:
        if not url:
            continue
        try:
            ics_text = fetch(url)
            ranges = extract_busy_ranges(ics_text)
            print(f"{name}: found {len(ranges)} booked range(s)")
            all_ranges.extend(ranges)
        except Exception as e:
            print(f"{name}: FAILED to fetch/parse ({e})", file=sys.stderr)

    unavailable_dates = expand_to_dates(all_ranges)

    data = {
        "_readme": "Auto-generated by sync_availability.py — do not edit by hand, it will be overwritten on the next sync.",
        "_last_synced": datetime.now(timezone.utc).isoformat(),
        "unavailable": unavailable_dates,
        "pending": []
    }

    os.makedirs(os.path.dirname(OUTPUT_PATH) or ".", exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    print(f"Wrote {len(unavailable_dates)} unavailable dates to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
